name: fractals2d
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  color: ^3.0.0
  fractal:
    path: '../fractal'
  crypto_fractal:
    path: '../crypto_fractal'
  sqlite3_flutter_libs: ^0.5.15
  sqlite3: ^2.1.0
  crypto: ^3.0.3

dev_dependencies:
  lints: ^5.1.1
